/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vault

import (
	"encoding/json"
)

// KvUndeleteRequest struct for KvUndeleteRequest
type KvUndeleteRequest struct {
	// The versions to unarchive. The versions will be restored and their data will be returned on normal get requests.
	Versions []int32 `json:"versions,omitempty"`
}

// NewKvUndeleteRequest instantiates a new KvUndeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKvUndeleteRequest() *KvUndeleteRequest {
	this := KvUndeleteRequest{}
	return &this
}

// NewKvUndeleteRequestWithDefaults instantiates a new KvUndeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKvUndeleteRequestWithDefaults() *KvUndeleteRequest {
	this := KvUndeleteRequest{}
	return &this
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *KvUndeleteRequest) GetVersions() []int32 {
	if o == nil || o.Versions == nil {
		var ret []int32
		return ret
	}
	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KvUndeleteRequest) GetVersionsOk() ([]int32, bool) {
	if o == nil || o.Versions == nil {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *KvUndeleteRequest) HasVersions() bool {
	if o != nil && o.Versions != nil {
		return true
	}

	return false
}

// SetVersions gets a reference to the given []int32 and assigns it to the Versions field.
func (o *KvUndeleteRequest) SetVersions(v []int32) {
	o.Versions = v
}

func (o KvUndeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Versions != nil {
		toSerialize["versions"] = o.Versions
	}
	return json.Marshal(toSerialize)
}

type NullableKvUndeleteRequest struct {
	value *KvUndeleteRequest
	isSet bool
}

func (v NullableKvUndeleteRequest) Get() *KvUndeleteRequest {
	return v.value
}

func (v *NullableKvUndeleteRequest) Set(val *KvUndeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKvUndeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKvUndeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKvUndeleteRequest(val *KvUndeleteRequest) *NullableKvUndeleteRequest {
	return &NullableKvUndeleteRequest{value: val, isSet: true}
}

func (v NullableKvUndeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKvUndeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


