/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vault

import (
	"encoding/json"
)

// SystemRevokePrefixRequest struct for SystemRevokePrefixRequest
type SystemRevokePrefixRequest struct {
	// Whether or not to perform the revocation synchronously
	Sync *bool `json:"sync,omitempty"`
}

// NewSystemRevokePrefixRequest instantiates a new SystemRevokePrefixRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemRevokePrefixRequest() *SystemRevokePrefixRequest {
	this := SystemRevokePrefixRequest{}
	var sync bool = true
	this.Sync = &sync
	return &this
}

// NewSystemRevokePrefixRequestWithDefaults instantiates a new SystemRevokePrefixRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemRevokePrefixRequestWithDefaults() *SystemRevokePrefixRequest {
	this := SystemRevokePrefixRequest{}
	var sync bool = true
	this.Sync = &sync
	return &this
}

// GetSync returns the Sync field value if set, zero value otherwise.
func (o *SystemRevokePrefixRequest) GetSync() bool {
	if o == nil || o.Sync == nil {
		var ret bool
		return ret
	}
	return *o.Sync
}

// GetSyncOk returns a tuple with the Sync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemRevokePrefixRequest) GetSyncOk() (*bool, bool) {
	if o == nil || o.Sync == nil {
		return nil, false
	}
	return o.Sync, true
}

// HasSync returns a boolean if a field has been set.
func (o *SystemRevokePrefixRequest) HasSync() bool {
	if o != nil && o.Sync != nil {
		return true
	}

	return false
}

// SetSync gets a reference to the given bool and assigns it to the Sync field.
func (o *SystemRevokePrefixRequest) SetSync(v bool) {
	o.Sync = &v
}

func (o SystemRevokePrefixRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Sync != nil {
		toSerialize["sync"] = o.Sync
	}
	return json.Marshal(toSerialize)
}

type NullableSystemRevokePrefixRequest struct {
	value *SystemRevokePrefixRequest
	isSet bool
}

func (v NullableSystemRevokePrefixRequest) Get() *SystemRevokePrefixRequest {
	return v.value
}

func (v *NullableSystemRevokePrefixRequest) Set(val *SystemRevokePrefixRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemRevokePrefixRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemRevokePrefixRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemRevokePrefixRequest(val *SystemRevokePrefixRequest) *NullableSystemRevokePrefixRequest {
	return &NullableSystemRevokePrefixRequest{value: val, isSet: true}
}

func (v NullableSystemRevokePrefixRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemRevokePrefixRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


