/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vault

import (
	"encoding/json"
)

// AwsConfigTidyIdentityAccesslistRequest struct for AwsConfigTidyIdentityAccesslistRequest
type AwsConfigTidyIdentityAccesslistRequest struct {
	// If set to 'true', disables the periodic tidying of the 'identity-accesslist/<instance_id>' entries.
	DisablePeriodicTidy *bool `json:"disable_periodic_tidy,omitempty"`
	// The amount of extra time that must have passed beyond the identity's expiration, before it is removed from the backend storage.
	SafetyBuffer *int32 `json:"safety_buffer,omitempty"`
}

// NewAwsConfigTidyIdentityAccesslistRequest instantiates a new AwsConfigTidyIdentityAccesslistRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsConfigTidyIdentityAccesslistRequest() *AwsConfigTidyIdentityAccesslistRequest {
	this := AwsConfigTidyIdentityAccesslistRequest{}
	var disablePeriodicTidy bool = false
	this.DisablePeriodicTidy = &disablePeriodicTidy
	var safetyBuffer int32 = 259200
	this.SafetyBuffer = &safetyBuffer
	return &this
}

// NewAwsConfigTidyIdentityAccesslistRequestWithDefaults instantiates a new AwsConfigTidyIdentityAccesslistRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsConfigTidyIdentityAccesslistRequestWithDefaults() *AwsConfigTidyIdentityAccesslistRequest {
	this := AwsConfigTidyIdentityAccesslistRequest{}
	var disablePeriodicTidy bool = false
	this.DisablePeriodicTidy = &disablePeriodicTidy
	var safetyBuffer int32 = 259200
	this.SafetyBuffer = &safetyBuffer
	return &this
}

// GetDisablePeriodicTidy returns the DisablePeriodicTidy field value if set, zero value otherwise.
func (o *AwsConfigTidyIdentityAccesslistRequest) GetDisablePeriodicTidy() bool {
	if o == nil || o.DisablePeriodicTidy == nil {
		var ret bool
		return ret
	}
	return *o.DisablePeriodicTidy
}

// GetDisablePeriodicTidyOk returns a tuple with the DisablePeriodicTidy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsConfigTidyIdentityAccesslistRequest) GetDisablePeriodicTidyOk() (*bool, bool) {
	if o == nil || o.DisablePeriodicTidy == nil {
		return nil, false
	}
	return o.DisablePeriodicTidy, true
}

// HasDisablePeriodicTidy returns a boolean if a field has been set.
func (o *AwsConfigTidyIdentityAccesslistRequest) HasDisablePeriodicTidy() bool {
	if o != nil && o.DisablePeriodicTidy != nil {
		return true
	}

	return false
}

// SetDisablePeriodicTidy gets a reference to the given bool and assigns it to the DisablePeriodicTidy field.
func (o *AwsConfigTidyIdentityAccesslistRequest) SetDisablePeriodicTidy(v bool) {
	o.DisablePeriodicTidy = &v
}

// GetSafetyBuffer returns the SafetyBuffer field value if set, zero value otherwise.
func (o *AwsConfigTidyIdentityAccesslistRequest) GetSafetyBuffer() int32 {
	if o == nil || o.SafetyBuffer == nil {
		var ret int32
		return ret
	}
	return *o.SafetyBuffer
}

// GetSafetyBufferOk returns a tuple with the SafetyBuffer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsConfigTidyIdentityAccesslistRequest) GetSafetyBufferOk() (*int32, bool) {
	if o == nil || o.SafetyBuffer == nil {
		return nil, false
	}
	return o.SafetyBuffer, true
}

// HasSafetyBuffer returns a boolean if a field has been set.
func (o *AwsConfigTidyIdentityAccesslistRequest) HasSafetyBuffer() bool {
	if o != nil && o.SafetyBuffer != nil {
		return true
	}

	return false
}

// SetSafetyBuffer gets a reference to the given int32 and assigns it to the SafetyBuffer field.
func (o *AwsConfigTidyIdentityAccesslistRequest) SetSafetyBuffer(v int32) {
	o.SafetyBuffer = &v
}

func (o AwsConfigTidyIdentityAccesslistRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DisablePeriodicTidy != nil {
		toSerialize["disable_periodic_tidy"] = o.DisablePeriodicTidy
	}
	if o.SafetyBuffer != nil {
		toSerialize["safety_buffer"] = o.SafetyBuffer
	}
	return json.Marshal(toSerialize)
}

type NullableAwsConfigTidyIdentityAccesslistRequest struct {
	value *AwsConfigTidyIdentityAccesslistRequest
	isSet bool
}

func (v NullableAwsConfigTidyIdentityAccesslistRequest) Get() *AwsConfigTidyIdentityAccesslistRequest {
	return v.value
}

func (v *NullableAwsConfigTidyIdentityAccesslistRequest) Set(val *AwsConfigTidyIdentityAccesslistRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsConfigTidyIdentityAccesslistRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsConfigTidyIdentityAccesslistRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsConfigTidyIdentityAccesslistRequest(val *AwsConfigTidyIdentityAccesslistRequest) *NullableAwsConfigTidyIdentityAccesslistRequest {
	return &NullableAwsConfigTidyIdentityAccesslistRequest{value: val, isSet: true}
}

func (v NullableAwsConfigTidyIdentityAccesslistRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsConfigTidyIdentityAccesslistRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


