/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vault

import (
	"encoding/json"
)

// PkiIssuerSignSelfIssuedRequest struct for PkiIssuerSignSelfIssuedRequest
type PkiIssuerSignSelfIssuedRequest struct {
	// PEM-format self-issued certificate to be signed.
	Certificate *string `json:"certificate,omitempty"`
	// If true, require the public key algorithm of the signer to match that of the self issued certificate.
	RequireMatchingCertificateAlgorithms *bool `json:"require_matching_certificate_algorithms,omitempty"`
}

// NewPkiIssuerSignSelfIssuedRequest instantiates a new PkiIssuerSignSelfIssuedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPkiIssuerSignSelfIssuedRequest() *PkiIssuerSignSelfIssuedRequest {
	this := PkiIssuerSignSelfIssuedRequest{}
	var requireMatchingCertificateAlgorithms bool = false
	this.RequireMatchingCertificateAlgorithms = &requireMatchingCertificateAlgorithms
	return &this
}

// NewPkiIssuerSignSelfIssuedRequestWithDefaults instantiates a new PkiIssuerSignSelfIssuedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPkiIssuerSignSelfIssuedRequestWithDefaults() *PkiIssuerSignSelfIssuedRequest {
	this := PkiIssuerSignSelfIssuedRequest{}
	var requireMatchingCertificateAlgorithms bool = false
	this.RequireMatchingCertificateAlgorithms = &requireMatchingCertificateAlgorithms
	return &this
}

// GetCertificate returns the Certificate field value if set, zero value otherwise.
func (o *PkiIssuerSignSelfIssuedRequest) GetCertificate() string {
	if o == nil || o.Certificate == nil {
		var ret string
		return ret
	}
	return *o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PkiIssuerSignSelfIssuedRequest) GetCertificateOk() (*string, bool) {
	if o == nil || o.Certificate == nil {
		return nil, false
	}
	return o.Certificate, true
}

// HasCertificate returns a boolean if a field has been set.
func (o *PkiIssuerSignSelfIssuedRequest) HasCertificate() bool {
	if o != nil && o.Certificate != nil {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given string and assigns it to the Certificate field.
func (o *PkiIssuerSignSelfIssuedRequest) SetCertificate(v string) {
	o.Certificate = &v
}

// GetRequireMatchingCertificateAlgorithms returns the RequireMatchingCertificateAlgorithms field value if set, zero value otherwise.
func (o *PkiIssuerSignSelfIssuedRequest) GetRequireMatchingCertificateAlgorithms() bool {
	if o == nil || o.RequireMatchingCertificateAlgorithms == nil {
		var ret bool
		return ret
	}
	return *o.RequireMatchingCertificateAlgorithms
}

// GetRequireMatchingCertificateAlgorithmsOk returns a tuple with the RequireMatchingCertificateAlgorithms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PkiIssuerSignSelfIssuedRequest) GetRequireMatchingCertificateAlgorithmsOk() (*bool, bool) {
	if o == nil || o.RequireMatchingCertificateAlgorithms == nil {
		return nil, false
	}
	return o.RequireMatchingCertificateAlgorithms, true
}

// HasRequireMatchingCertificateAlgorithms returns a boolean if a field has been set.
func (o *PkiIssuerSignSelfIssuedRequest) HasRequireMatchingCertificateAlgorithms() bool {
	if o != nil && o.RequireMatchingCertificateAlgorithms != nil {
		return true
	}

	return false
}

// SetRequireMatchingCertificateAlgorithms gets a reference to the given bool and assigns it to the RequireMatchingCertificateAlgorithms field.
func (o *PkiIssuerSignSelfIssuedRequest) SetRequireMatchingCertificateAlgorithms(v bool) {
	o.RequireMatchingCertificateAlgorithms = &v
}

func (o PkiIssuerSignSelfIssuedRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Certificate != nil {
		toSerialize["certificate"] = o.Certificate
	}
	if o.RequireMatchingCertificateAlgorithms != nil {
		toSerialize["require_matching_certificate_algorithms"] = o.RequireMatchingCertificateAlgorithms
	}
	return json.Marshal(toSerialize)
}

type NullablePkiIssuerSignSelfIssuedRequest struct {
	value *PkiIssuerSignSelfIssuedRequest
	isSet bool
}

func (v NullablePkiIssuerSignSelfIssuedRequest) Get() *PkiIssuerSignSelfIssuedRequest {
	return v.value
}

func (v *NullablePkiIssuerSignSelfIssuedRequest) Set(val *PkiIssuerSignSelfIssuedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePkiIssuerSignSelfIssuedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePkiIssuerSignSelfIssuedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePkiIssuerSignSelfIssuedRequest(val *PkiIssuerSignSelfIssuedRequest) *NullablePkiIssuerSignSelfIssuedRequest {
	return &NullablePkiIssuerSignSelfIssuedRequest{value: val, isSet: true}
}

func (v NullablePkiIssuerSignSelfIssuedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePkiIssuerSignSelfIssuedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


