/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vault

import (
	"encoding/json"
)

// AwsCredsRequest struct for AwsCredsRequest
type AwsCredsRequest struct {
	// Name of the role
	Name *string `json:"name,omitempty"`
	// ARN of role to assume when credential_type is assumed_role
	RoleArn *string `json:"role_arn,omitempty"`
	// Session name to use when assuming role. Max chars: 64
	RoleSessionName *string `json:"role_session_name,omitempty"`
	// Lifetime of the returned credentials in seconds
	Ttl *int32 `json:"ttl,omitempty"`
}

// NewAwsCredsRequest instantiates a new AwsCredsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsCredsRequest() *AwsCredsRequest {
	this := AwsCredsRequest{}
	var ttl int32 = 3600
	this.Ttl = &ttl
	return &this
}

// NewAwsCredsRequestWithDefaults instantiates a new AwsCredsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsCredsRequestWithDefaults() *AwsCredsRequest {
	this := AwsCredsRequest{}
	var ttl int32 = 3600
	this.Ttl = &ttl
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AwsCredsRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsCredsRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AwsCredsRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AwsCredsRequest) SetName(v string) {
	o.Name = &v
}

// GetRoleArn returns the RoleArn field value if set, zero value otherwise.
func (o *AwsCredsRequest) GetRoleArn() string {
	if o == nil || o.RoleArn == nil {
		var ret string
		return ret
	}
	return *o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsCredsRequest) GetRoleArnOk() (*string, bool) {
	if o == nil || o.RoleArn == nil {
		return nil, false
	}
	return o.RoleArn, true
}

// HasRoleArn returns a boolean if a field has been set.
func (o *AwsCredsRequest) HasRoleArn() bool {
	if o != nil && o.RoleArn != nil {
		return true
	}

	return false
}

// SetRoleArn gets a reference to the given string and assigns it to the RoleArn field.
func (o *AwsCredsRequest) SetRoleArn(v string) {
	o.RoleArn = &v
}

// GetRoleSessionName returns the RoleSessionName field value if set, zero value otherwise.
func (o *AwsCredsRequest) GetRoleSessionName() string {
	if o == nil || o.RoleSessionName == nil {
		var ret string
		return ret
	}
	return *o.RoleSessionName
}

// GetRoleSessionNameOk returns a tuple with the RoleSessionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsCredsRequest) GetRoleSessionNameOk() (*string, bool) {
	if o == nil || o.RoleSessionName == nil {
		return nil, false
	}
	return o.RoleSessionName, true
}

// HasRoleSessionName returns a boolean if a field has been set.
func (o *AwsCredsRequest) HasRoleSessionName() bool {
	if o != nil && o.RoleSessionName != nil {
		return true
	}

	return false
}

// SetRoleSessionName gets a reference to the given string and assigns it to the RoleSessionName field.
func (o *AwsCredsRequest) SetRoleSessionName(v string) {
	o.RoleSessionName = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *AwsCredsRequest) GetTtl() int32 {
	if o == nil || o.Ttl == nil {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsCredsRequest) GetTtlOk() (*int32, bool) {
	if o == nil || o.Ttl == nil {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *AwsCredsRequest) HasTtl() bool {
	if o != nil && o.Ttl != nil {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *AwsCredsRequest) SetTtl(v int32) {
	o.Ttl = &v
}

func (o AwsCredsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.RoleArn != nil {
		toSerialize["role_arn"] = o.RoleArn
	}
	if o.RoleSessionName != nil {
		toSerialize["role_session_name"] = o.RoleSessionName
	}
	if o.Ttl != nil {
		toSerialize["ttl"] = o.Ttl
	}
	return json.Marshal(toSerialize)
}

type NullableAwsCredsRequest struct {
	value *AwsCredsRequest
	isSet bool
}

func (v NullableAwsCredsRequest) Get() *AwsCredsRequest {
	return v.value
}

func (v *NullableAwsCredsRequest) Set(val *AwsCredsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsCredsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsCredsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsCredsRequest(val *AwsCredsRequest) *NullableAwsCredsRequest {
	return &NullableAwsCredsRequest{value: val, isSet: true}
}

func (v NullableAwsCredsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsCredsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


