/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vault

import (
	"encoding/json"
)

// ApproleRoleCustomSecretIdRequest struct for ApproleRoleCustomSecretIdRequest
type ApproleRoleCustomSecretIdRequest struct {
	// Comma separated string or list of CIDR blocks enforcing secret IDs to be used from specific set of IP addresses. If 'bound_cidr_list' is set on the role, then the list of CIDR blocks listed here should be a subset of the CIDR blocks listed on the role.
	CidrList []string `json:"cidr_list,omitempty"`
	// Metadata to be tied to the SecretID. This should be a JSON formatted string containing metadata in key value pairs.
	Metadata *string `json:"metadata,omitempty"`
	// SecretID to be attached to the role.
	SecretId *string `json:"secret_id,omitempty"`
	// Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can use the returned token. Should be a subset of the token CIDR blocks listed on the role, if any.
	TokenBoundCidrs []string `json:"token_bound_cidrs,omitempty"`
}

// NewApproleRoleCustomSecretIdRequest instantiates a new ApproleRoleCustomSecretIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproleRoleCustomSecretIdRequest() *ApproleRoleCustomSecretIdRequest {
	this := ApproleRoleCustomSecretIdRequest{}
	return &this
}

// NewApproleRoleCustomSecretIdRequestWithDefaults instantiates a new ApproleRoleCustomSecretIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproleRoleCustomSecretIdRequestWithDefaults() *ApproleRoleCustomSecretIdRequest {
	this := ApproleRoleCustomSecretIdRequest{}
	return &this
}

// GetCidrList returns the CidrList field value if set, zero value otherwise.
func (o *ApproleRoleCustomSecretIdRequest) GetCidrList() []string {
	if o == nil || o.CidrList == nil {
		var ret []string
		return ret
	}
	return o.CidrList
}

// GetCidrListOk returns a tuple with the CidrList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApproleRoleCustomSecretIdRequest) GetCidrListOk() ([]string, bool) {
	if o == nil || o.CidrList == nil {
		return nil, false
	}
	return o.CidrList, true
}

// HasCidrList returns a boolean if a field has been set.
func (o *ApproleRoleCustomSecretIdRequest) HasCidrList() bool {
	if o != nil && o.CidrList != nil {
		return true
	}

	return false
}

// SetCidrList gets a reference to the given []string and assigns it to the CidrList field.
func (o *ApproleRoleCustomSecretIdRequest) SetCidrList(v []string) {
	o.CidrList = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ApproleRoleCustomSecretIdRequest) GetMetadata() string {
	if o == nil || o.Metadata == nil {
		var ret string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApproleRoleCustomSecretIdRequest) GetMetadataOk() (*string, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ApproleRoleCustomSecretIdRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given string and assigns it to the Metadata field.
func (o *ApproleRoleCustomSecretIdRequest) SetMetadata(v string) {
	o.Metadata = &v
}

// GetSecretId returns the SecretId field value if set, zero value otherwise.
func (o *ApproleRoleCustomSecretIdRequest) GetSecretId() string {
	if o == nil || o.SecretId == nil {
		var ret string
		return ret
	}
	return *o.SecretId
}

// GetSecretIdOk returns a tuple with the SecretId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApproleRoleCustomSecretIdRequest) GetSecretIdOk() (*string, bool) {
	if o == nil || o.SecretId == nil {
		return nil, false
	}
	return o.SecretId, true
}

// HasSecretId returns a boolean if a field has been set.
func (o *ApproleRoleCustomSecretIdRequest) HasSecretId() bool {
	if o != nil && o.SecretId != nil {
		return true
	}

	return false
}

// SetSecretId gets a reference to the given string and assigns it to the SecretId field.
func (o *ApproleRoleCustomSecretIdRequest) SetSecretId(v string) {
	o.SecretId = &v
}

// GetTokenBoundCidrs returns the TokenBoundCidrs field value if set, zero value otherwise.
func (o *ApproleRoleCustomSecretIdRequest) GetTokenBoundCidrs() []string {
	if o == nil || o.TokenBoundCidrs == nil {
		var ret []string
		return ret
	}
	return o.TokenBoundCidrs
}

// GetTokenBoundCidrsOk returns a tuple with the TokenBoundCidrs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApproleRoleCustomSecretIdRequest) GetTokenBoundCidrsOk() ([]string, bool) {
	if o == nil || o.TokenBoundCidrs == nil {
		return nil, false
	}
	return o.TokenBoundCidrs, true
}

// HasTokenBoundCidrs returns a boolean if a field has been set.
func (o *ApproleRoleCustomSecretIdRequest) HasTokenBoundCidrs() bool {
	if o != nil && o.TokenBoundCidrs != nil {
		return true
	}

	return false
}

// SetTokenBoundCidrs gets a reference to the given []string and assigns it to the TokenBoundCidrs field.
func (o *ApproleRoleCustomSecretIdRequest) SetTokenBoundCidrs(v []string) {
	o.TokenBoundCidrs = v
}

func (o ApproleRoleCustomSecretIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CidrList != nil {
		toSerialize["cidr_list"] = o.CidrList
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.SecretId != nil {
		toSerialize["secret_id"] = o.SecretId
	}
	if o.TokenBoundCidrs != nil {
		toSerialize["token_bound_cidrs"] = o.TokenBoundCidrs
	}
	return json.Marshal(toSerialize)
}

type NullableApproleRoleCustomSecretIdRequest struct {
	value *ApproleRoleCustomSecretIdRequest
	isSet bool
}

func (v NullableApproleRoleCustomSecretIdRequest) Get() *ApproleRoleCustomSecretIdRequest {
	return v.value
}

func (v *NullableApproleRoleCustomSecretIdRequest) Set(val *ApproleRoleCustomSecretIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApproleRoleCustomSecretIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApproleRoleCustomSecretIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproleRoleCustomSecretIdRequest(val *ApproleRoleCustomSecretIdRequest) *NullableApproleRoleCustomSecretIdRequest {
	return &NullableApproleRoleCustomSecretIdRequest{value: val, isSet: true}
}

func (v NullableApproleRoleCustomSecretIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproleRoleCustomSecretIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


