/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vault

import (
	"encoding/json"
)

// IdentityGroupAliasIdRequest struct for IdentityGroupAliasIdRequest
type IdentityGroupAliasIdRequest struct {
	// ID of the group to which this is an alias.
	CanonicalId *string `json:"canonical_id,omitempty"`
	// Mount accessor to which this alias belongs to.
	MountAccessor *string `json:"mount_accessor,omitempty"`
	// Alias of the group.
	Name *string `json:"name,omitempty"`
}

// NewIdentityGroupAliasIdRequest instantiates a new IdentityGroupAliasIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityGroupAliasIdRequest() *IdentityGroupAliasIdRequest {
	this := IdentityGroupAliasIdRequest{}
	return &this
}

// NewIdentityGroupAliasIdRequestWithDefaults instantiates a new IdentityGroupAliasIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityGroupAliasIdRequestWithDefaults() *IdentityGroupAliasIdRequest {
	this := IdentityGroupAliasIdRequest{}
	return &this
}

// GetCanonicalId returns the CanonicalId field value if set, zero value otherwise.
func (o *IdentityGroupAliasIdRequest) GetCanonicalId() string {
	if o == nil || o.CanonicalId == nil {
		var ret string
		return ret
	}
	return *o.CanonicalId
}

// GetCanonicalIdOk returns a tuple with the CanonicalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityGroupAliasIdRequest) GetCanonicalIdOk() (*string, bool) {
	if o == nil || o.CanonicalId == nil {
		return nil, false
	}
	return o.CanonicalId, true
}

// HasCanonicalId returns a boolean if a field has been set.
func (o *IdentityGroupAliasIdRequest) HasCanonicalId() bool {
	if o != nil && o.CanonicalId != nil {
		return true
	}

	return false
}

// SetCanonicalId gets a reference to the given string and assigns it to the CanonicalId field.
func (o *IdentityGroupAliasIdRequest) SetCanonicalId(v string) {
	o.CanonicalId = &v
}

// GetMountAccessor returns the MountAccessor field value if set, zero value otherwise.
func (o *IdentityGroupAliasIdRequest) GetMountAccessor() string {
	if o == nil || o.MountAccessor == nil {
		var ret string
		return ret
	}
	return *o.MountAccessor
}

// GetMountAccessorOk returns a tuple with the MountAccessor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityGroupAliasIdRequest) GetMountAccessorOk() (*string, bool) {
	if o == nil || o.MountAccessor == nil {
		return nil, false
	}
	return o.MountAccessor, true
}

// HasMountAccessor returns a boolean if a field has been set.
func (o *IdentityGroupAliasIdRequest) HasMountAccessor() bool {
	if o != nil && o.MountAccessor != nil {
		return true
	}

	return false
}

// SetMountAccessor gets a reference to the given string and assigns it to the MountAccessor field.
func (o *IdentityGroupAliasIdRequest) SetMountAccessor(v string) {
	o.MountAccessor = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IdentityGroupAliasIdRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityGroupAliasIdRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IdentityGroupAliasIdRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IdentityGroupAliasIdRequest) SetName(v string) {
	o.Name = &v
}

func (o IdentityGroupAliasIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CanonicalId != nil {
		toSerialize["canonical_id"] = o.CanonicalId
	}
	if o.MountAccessor != nil {
		toSerialize["mount_accessor"] = o.MountAccessor
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableIdentityGroupAliasIdRequest struct {
	value *IdentityGroupAliasIdRequest
	isSet bool
}

func (v NullableIdentityGroupAliasIdRequest) Get() *IdentityGroupAliasIdRequest {
	return v.value
}

func (v *NullableIdentityGroupAliasIdRequest) Set(val *IdentityGroupAliasIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityGroupAliasIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityGroupAliasIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityGroupAliasIdRequest(val *IdentityGroupAliasIdRequest) *NullableIdentityGroupAliasIdRequest {
	return &NullableIdentityGroupAliasIdRequest{value: val, isSet: true}
}

func (v NullableIdentityGroupAliasIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityGroupAliasIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


