/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vault

import (
	"encoding/json"
)

// ApproleRoleSecretIdAccessorDestroyRequest struct for ApproleRoleSecretIdAccessorDestroyRequest
type ApproleRoleSecretIdAccessorDestroyRequest struct {
	// Accessor of the SecretID
	SecretIdAccessor *string `json:"secret_id_accessor,omitempty"`
}

// NewApproleRoleSecretIdAccessorDestroyRequest instantiates a new ApproleRoleSecretIdAccessorDestroyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproleRoleSecretIdAccessorDestroyRequest() *ApproleRoleSecretIdAccessorDestroyRequest {
	this := ApproleRoleSecretIdAccessorDestroyRequest{}
	return &this
}

// NewApproleRoleSecretIdAccessorDestroyRequestWithDefaults instantiates a new ApproleRoleSecretIdAccessorDestroyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproleRoleSecretIdAccessorDestroyRequestWithDefaults() *ApproleRoleSecretIdAccessorDestroyRequest {
	this := ApproleRoleSecretIdAccessorDestroyRequest{}
	return &this
}

// GetSecretIdAccessor returns the SecretIdAccessor field value if set, zero value otherwise.
func (o *ApproleRoleSecretIdAccessorDestroyRequest) GetSecretIdAccessor() string {
	if o == nil || o.SecretIdAccessor == nil {
		var ret string
		return ret
	}
	return *o.SecretIdAccessor
}

// GetSecretIdAccessorOk returns a tuple with the SecretIdAccessor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApproleRoleSecretIdAccessorDestroyRequest) GetSecretIdAccessorOk() (*string, bool) {
	if o == nil || o.SecretIdAccessor == nil {
		return nil, false
	}
	return o.SecretIdAccessor, true
}

// HasSecretIdAccessor returns a boolean if a field has been set.
func (o *ApproleRoleSecretIdAccessorDestroyRequest) HasSecretIdAccessor() bool {
	if o != nil && o.SecretIdAccessor != nil {
		return true
	}

	return false
}

// SetSecretIdAccessor gets a reference to the given string and assigns it to the SecretIdAccessor field.
func (o *ApproleRoleSecretIdAccessorDestroyRequest) SetSecretIdAccessor(v string) {
	o.SecretIdAccessor = &v
}

func (o ApproleRoleSecretIdAccessorDestroyRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SecretIdAccessor != nil {
		toSerialize["secret_id_accessor"] = o.SecretIdAccessor
	}
	return json.Marshal(toSerialize)
}

type NullableApproleRoleSecretIdAccessorDestroyRequest struct {
	value *ApproleRoleSecretIdAccessorDestroyRequest
	isSet bool
}

func (v NullableApproleRoleSecretIdAccessorDestroyRequest) Get() *ApproleRoleSecretIdAccessorDestroyRequest {
	return v.value
}

func (v *NullableApproleRoleSecretIdAccessorDestroyRequest) Set(val *ApproleRoleSecretIdAccessorDestroyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApproleRoleSecretIdAccessorDestroyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApproleRoleSecretIdAccessorDestroyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproleRoleSecretIdAccessorDestroyRequest(val *ApproleRoleSecretIdAccessorDestroyRequest) *NullableApproleRoleSecretIdAccessorDestroyRequest {
	return &NullableApproleRoleSecretIdAccessorDestroyRequest{value: val, isSet: true}
}

func (v NullableApproleRoleSecretIdAccessorDestroyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproleRoleSecretIdAccessorDestroyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


