/*

HashiCorp Vault API



HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.



API version: 1.13.0


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"encoding/json"
)

// AppRoleReadPoliciesResponse struct for AppRoleReadPoliciesResponse
type AppRoleReadPoliciesResponse struct {
	// Use \"token_policies\" instead. If this and \"token_policies\" are both specified, only \"token_policies\" will be used.

	// Deprecated

	Policies []string `json:"policies"`

	// Comma-separated list of policies

	TokenPolicies []string `json:"token_policies"`
}

// NewAppRoleReadPoliciesResponseWithDefaults instantiates a new AppRoleReadPoliciesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppRoleReadPoliciesResponseWithDefaults() *AppRoleReadPoliciesResponse {
	var this AppRoleReadPoliciesResponse

	return &this
}

func (o AppRoleReadPoliciesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := make(map[string]interface{})

	toSerialize["policies"] = o.Policies

	toSerialize["token_policies"] = o.TokenPolicies

	return json.Marshal(toSerialize)
}
