/*

HashiCorp Vault API



HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.



API version: 1.13.0


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"encoding/json"
)

// TransitImportKeyVersionRequest struct for TransitImportKeyVersionRequest
type TransitImportKeyVersionRequest struct {
	// The base64-encoded ciphertext of the keys. The AES key should be encrypted using OAEP with the wrapping key and then concatenated with the import key, wrapped by the AES key.

	Ciphertext string `json:"ciphertext"`

	// The hash function used as a random oracle in the OAEP wrapping of the user-generated, ephemeral AES key. Can be one of \"SHA1\", \"SHA224\", \"SHA256\" (default), \"SHA384\", or \"SHA512\"

	HashFunction string `json:"hash_function"`
}

// NewTransitImportKeyVersionRequestWithDefaults instantiates a new TransitImportKeyVersionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransitImportKeyVersionRequestWithDefaults() *TransitImportKeyVersionRequest {
	var this TransitImportKeyVersionRequest

	this.HashFunction = "SHA256"

	return &this
}

func (o TransitImportKeyVersionRequest) MarshalJSON() ([]byte, error) {
	toSerialize := make(map[string]interface{})

	toSerialize["ciphertext"] = o.Ciphertext

	toSerialize["hash_function"] = o.HashFunction

	return json.Marshal(toSerialize)
}
