/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"encoding/json"
)

// WrappingRewrapRequest struct for WrappingRewrapRequest
type WrappingRewrapRequest struct {
	Token string `json:"token"`
}

// NewWrappingRewrapRequestWithDefaults instantiates a new WrappingRewrapRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWrappingRewrapRequestWithDefaults() *WrappingRewrapRequest {
	var this WrappingRewrapRequest

	return &this
}

func (o WrappingRewrapRequest) MarshalJSON() ([]byte, error) {
	toSerialize := make(map[string]interface{})

	toSerialize["token"] = o.Token

	return json.Marshal(toSerialize)
}
