/*

HashiCorp Vault API



HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.



API version: 1.13.0


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"encoding/json"
)

// RemountRequest struct for RemountRequest
type RemountRequest struct {
	// The previous mount point.

	From string `json:"from"`

	// The new mount point.

	To string `json:"to"`
}

// NewRemountRequestWithDefaults instantiates a new RemountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemountRequestWithDefaults() *RemountRequest {
	var this RemountRequest

	return &this
}

func (o RemountRequest) MarshalJSON() ([]byte, error) {
	toSerialize := make(map[string]interface{})

	toSerialize["from"] = o.From

	toSerialize["to"] = o.To

	return json.Marshal(toSerialize)
}
