/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"encoding/json"
)

// AWSConfigWriteLeaseRequest struct for AWSConfigWriteLeaseRequest
type AWSConfigWriteLeaseRequest struct {
	// Default lease for roles.
	Lease string `json:"lease"`
	// Maximum time a credential is valid for.
	LeaseMax string `json:"lease_max"`
}

// NewAWSConfigWriteLeaseRequestWithDefaults instantiates a new AWSConfigWriteLeaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSConfigWriteLeaseRequestWithDefaults() *AWSConfigWriteLeaseRequest {
	var this AWSConfigWriteLeaseRequest

	return &this
}

func (o AWSConfigWriteLeaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize := make(map[string]interface{})

	toSerialize["lease"] = o.Lease
	toSerialize["lease_max"] = o.LeaseMax

	return json.Marshal(toSerialize)
}
