/*
HashiCorp Vault API

HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"encoding/json"
)

// NomadWriteLeaseConfigRequest struct for NomadWriteLeaseConfigRequest
type NomadWriteLeaseConfigRequest struct {
	// Duration after which the issued token should not be allowed to be renewed
	MaxTtl int32 `json:"max_ttl"`
	// Duration before which the issued token needs renewal
	Ttl int32 `json:"ttl"`
}

// NewNomadWriteLeaseConfigRequestWithDefaults instantiates a new NomadWriteLeaseConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNomadWriteLeaseConfigRequestWithDefaults() *NomadWriteLeaseConfigRequest {
	var this NomadWriteLeaseConfigRequest

	return &this
}

func (o NomadWriteLeaseConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize := make(map[string]interface{})

	toSerialize["max_ttl"] = o.MaxTtl
	toSerialize["ttl"] = o.Ttl

	return json.Marshal(toSerialize)
}
